language: python
python:
  - 2.7

# command to install dependencies
install:
  - "pip install --use-mirrors jinja2 werkzeug flask django pycrypto"
  - "pip install . --use-mirrors"


# command to run tests
script: run-tests.py

notifications:
  email: false