language: python
python:
  - 3.3

# command to install dependencies
install:
  - "pip install --use-mirrors jinja2 werkzeug flask django pycrypto"
  - "pip install . --use-mirrors"


# command to run tests
script: make tests

notifications:
  email: false